# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(743, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(743, 444))
        MainWindow.setMaximumSize(QtCore.QSize(743, 444))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 801, 401))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(290, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.name_lineEdit.setGeometry(QtCore.QRect(340, 10, 363, 21))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.saveaction_Button = QtWidgets.QPushButton(self.tab)
        self.saveaction_Button.setGeometry(QtCore.QRect(290, 360, 201, 21))
        self.saveaction_Button.setObjectName("saveaction_Button")
        self.add_delay_Button = QtWidgets.QPushButton(self.tab)
        self.add_delay_Button.setGeometry(QtCore.QRect(200, 360, 71, 21))
        self.add_delay_Button.setObjectName("add_delay_Button")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 360, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.actions_listWidget = QtWidgets.QListWidget(self.tab)
        self.actions_listWidget.setGeometry(QtCore.QRect(10, 10, 261, 301))
        self.actions_listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.actions_listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.actions_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.actions_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.actions_listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.actions_listWidget.setObjectName("actions_listWidget")
        self.delete_action_pushButton = QtWidgets.QPushButton(self.tab)
        self.delete_action_pushButton.setGeometry(QtCore.QRect(10, 310, 131, 21))
        self.delete_action_pushButton.setObjectName("delete_action_pushButton")
        self.delay_SpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.delay_SpinBox.setGeometry(QtCore.QRect(50, 360, 141, 22))
        self.delay_SpinBox.setMaximum(10000.0)
        self.delay_SpinBox.setObjectName("delay_SpinBox")
        self.actions_tabWidget = QtWidgets.QTabWidget(self.tab)
        self.actions_tabWidget.setEnabled(True)
        self.actions_tabWidget.setGeometry(QtCore.QRect(290, 40, 413, 311))
        self.actions_tabWidget.setObjectName("actions_tabWidget")
        self.click_tab = QtWidgets.QWidget()
        self.click_tab.setEnabled(True)
        self.click_tab.setObjectName("click_tab")
        self.label_2 = QtWidgets.QLabel(self.click_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.click_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_comboBox = QtWidgets.QComboBox(self.click_tab)
        self.button_comboBox.setGeometry(QtCore.QRect(60, 40, 181, 22))
        self.button_comboBox.setObjectName("button_comboBox")
        self.button_comboBox.addItem("")
        self.button_comboBox.addItem("")
        self.button_comboBox.addItem("")
        self.image_comboBox = QtWidgets.QComboBox(self.click_tab)
        self.image_comboBox.setGeometry(QtCore.QRect(60, 10, 181, 22))
        self.image_comboBox.setObjectName("image_comboBox")
        self.image_comboBox.addItem("")
        self.image_comboBox.setItemText(0, "")
        self.label_12 = QtWidgets.QLabel(self.click_tab)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.duration_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.click_tab)
        self.duration_doubleSpinBox.setGeometry(QtCore.QRect(110, 100, 131, 22))
        self.duration_doubleSpinBox.setObjectName("duration_doubleSpinBox")
        self.label_16 = QtWidgets.QLabel(self.click_tab)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.threshold_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.click_tab)
        self.threshold_doubleSpinBox.setGeometry(QtCore.QRect(110, 70, 131, 22))
        self.threshold_doubleSpinBox.setMaximum(0.9)
        self.threshold_doubleSpinBox.setObjectName("threshold_doubleSpinBox")
        self.label_50 = QtWidgets.QLabel(self.click_tab)
        self.label_50.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.clicknum_spinBox = QtWidgets.QSpinBox(self.click_tab)
        self.clicknum_spinBox.setGeometry(QtCore.QRect(110, 130, 131, 22))
        self.clicknum_spinBox.setObjectName("clicknum_spinBox")
        self.label_51 = QtWidgets.QLabel(self.click_tab)
        self.label_51.setGeometry(QtCore.QRect(10, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.interval_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.click_tab)
        self.interval_doubleSpinBox.setGeometry(QtCore.QRect(110, 160, 131, 22))
        self.interval_doubleSpinBox.setObjectName("interval_doubleSpinBox")
        self.index_spinBox = QtWidgets.QSpinBox(self.click_tab)
        self.index_spinBox.setGeometry(QtCore.QRect(110, 190, 131, 22))
        self.index_spinBox.setObjectName("index_spinBox")
        self.label_55 = QtWidgets.QLabel(self.click_tab)
        self.label_55.setGeometry(QtCore.QRect(10, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.actions_tabWidget.addTab(self.click_tab, "")
        self.print_tab = QtWidgets.QWidget()
        self.print_tab.setObjectName("print_tab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.print_tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_54 = QtWidgets.QLabel(self.print_tab)
        self.label_54.setGeometry(QtCore.QRect(10, 260, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.interval_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.print_tab)
        self.interval_doubleSpinBox_2.setGeometry(QtCore.QRect(70, 260, 131, 22))
        self.interval_doubleSpinBox_2.setObjectName("interval_doubleSpinBox_2")
        self.actions_tabWidget.addTab(self.print_tab, "")
        self.press_tab = QtWidgets.QWidget()
        self.press_tab.setObjectName("press_tab")
        self.hotkeys_listWidget = QtWidgets.QListWidget(self.press_tab)
        self.hotkeys_listWidget.setGeometry(QtCore.QRect(10, 10, 111, 251))
        self.hotkeys_listWidget.setObjectName("hotkeys_listWidget")
        self.hotkey_comboBox = QtWidgets.QComboBox(self.press_tab)
        self.hotkey_comboBox.setGeometry(QtCore.QRect(140, 10, 141, 22))
        self.hotkey_comboBox.setObjectName("hotkey_comboBox")
        self.add_hotkey_pushButton = QtWidgets.QPushButton(self.press_tab)
        self.add_hotkey_pushButton.setGeometry(QtCore.QRect(140, 40, 141, 21))
        self.add_hotkey_pushButton.setObjectName("add_hotkey_pushButton")
        self.hotkey_lineEdit = QtWidgets.QLineEdit(self.press_tab)
        self.hotkey_lineEdit.setGeometry(QtCore.QRect(140, 80, 141, 21))
        self.hotkey_lineEdit.setMaxLength(1)
        self.hotkey_lineEdit.setObjectName("hotkey_lineEdit")
        self.add_hotkey_symbol_pushButton = QtWidgets.QPushButton(self.press_tab)
        self.add_hotkey_symbol_pushButton.setGeometry(QtCore.QRect(140, 110, 141, 21))
        self.add_hotkey_symbol_pushButton.setObjectName("add_hotkey_symbol_pushButton")
        self.delete_hotkey_pushButton = QtWidgets.QPushButton(self.press_tab)
        self.delete_hotkey_pushButton.setGeometry(QtCore.QRect(10, 260, 111, 21))
        self.delete_hotkey_pushButton.setObjectName("delete_hotkey_pushButton")
        self.actions_tabWidget.addTab(self.press_tab, "")
        self.scroll_tab = QtWidgets.QWidget()
        self.scroll_tab.setObjectName("scroll_tab")
        self.scroll_spinBox = QtWidgets.QSpinBox(self.scroll_tab)
        self.scroll_spinBox.setGeometry(QtCore.QRect(10, 10, 111, 22))
        self.scroll_spinBox.setObjectName("scroll_spinBox")
        self.actions_tabWidget.addTab(self.scroll_tab, "")
        self.draganddrop_tab = QtWidgets.QWidget()
        self.draganddrop_tab.setObjectName("draganddrop_tab")
        self.label_4 = QtWidgets.QLabel(self.draganddrop_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.image_dad_comboBox = QtWidgets.QComboBox(self.draganddrop_tab)
        self.image_dad_comboBox.setGeometry(QtCore.QRect(80, 10, 201, 22))
        self.image_dad_comboBox.setObjectName("image_dad_comboBox")
        self.image_dad_comboBox.addItem("")
        self.image_dad_comboBox.setItemText(0, "")
        self.duration_dad_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.draganddrop_tab)
        self.duration_dad_doubleSpinBox.setGeometry(QtCore.QRect(80, 40, 201, 22))
        self.duration_dad_doubleSpinBox.setObjectName("duration_dad_doubleSpinBox")
        self.label_18 = QtWidgets.QLabel(self.draganddrop_tab)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.draganddrop_tab)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.threshold_dad_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.draganddrop_tab)
        self.threshold_dad_doubleSpinBox.setGeometry(QtCore.QRect(80, 70, 201, 22))
        self.threshold_dad_doubleSpinBox.setObjectName("threshold_dad_doubleSpinBox")
        self.label_20 = QtWidgets.QLabel(self.draganddrop_tab)
        self.label_20.setGeometry(QtCore.QRect(10, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.index_dad_spinBox = QtWidgets.QSpinBox(self.draganddrop_tab)
        self.index_dad_spinBox.setGeometry(QtCore.QRect(80, 100, 201, 22))
        self.index_dad_spinBox.setObjectName("index_dad_spinBox")
        self.actions_tabWidget.addTab(self.draganddrop_tab, "")
        self.copy_action_pushButton = QtWidgets.QPushButton(self.tab)
        self.copy_action_pushButton.setGeometry(QtCore.QRect(140, 310, 131, 21))
        self.copy_action_pushButton.setObjectName("copy_action_pushButton")
        self.new_action_puchButton = QtWidgets.QPushButton(self.tab)
        self.new_action_puchButton.setGeometry(QtCore.QRect(10, 330, 261, 21))
        self.new_action_puchButton.setObjectName("new_action_puchButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.startstop_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.startstop_comboBox.setGeometry(QtCore.QRect(150, 10, 61, 22))
        self.startstop_comboBox.setCurrentText("")
        self.startstop_comboBox.setObjectName("startstop_comboBox")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(20, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.start_Button = QtWidgets.QPushButton(self.tab_2)
        self.start_Button.setGeometry(QtCore.QRect(20, 220, 171, 21))
        self.start_Button.setObjectName("start_Button")
        self.display_info_checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.display_info_checkBox.setGeometry(QtCore.QRect(150, 130, 16, 19))
        self.display_info_checkBox.setText("")
        self.display_info_checkBox.setObjectName("display_info_checkBox")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cycle_checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.cycle_checkBox.setGeometry(QtCore.QRect(150, 160, 21, 19))
        self.cycle_checkBox.setText("")
        self.cycle_checkBox.setObjectName("cycle_checkBox")
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(20, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.pause_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.pause_comboBox.setGeometry(QtCore.QRect(150, 40, 61, 22))
        self.pause_comboBox.setObjectName("pause_comboBox")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.actions_interval_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.actions_interval_doubleSpinBox.setGeometry(QtCore.QRect(150, 70, 62, 22))
        self.actions_interval_doubleSpinBox.setObjectName("actions_interval_doubleSpinBox")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.disable_mouse_checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.disable_mouse_checkBox.setGeometry(QtCore.QRect(150, 100, 21, 19))
        self.disable_mouse_checkBox.setText("")
        self.disable_mouse_checkBox.setObjectName("disable_mouse_checkBox")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 185, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(150, 190, 21, 19))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.save_Button = QtWidgets.QPushButton(self.centralwidget)
        self.save_Button.setGeometry(QtCore.QRect(90, 10, 31, 31))
        self.save_Button.setText("")
        self.save_Button.setObjectName("save_Button")
        self.open_Button = QtWidgets.QPushButton(self.centralwidget)
        self.open_Button.setGeometry(QtCore.QRect(50, 10, 31, 31))
        self.open_Button.setText("")
        self.open_Button.setObjectName("open_Button")
        self.info_Button = QtWidgets.QPushButton(self.centralwidget)
        self.info_Button.setGeometry(QtCore.QRect(700, 10, 31, 31))
        self.info_Button.setText("")
        self.info_Button.setObjectName("info_Button")
        self.newfile_Button = QtWidgets.QPushButton(self.centralwidget)
        self.newfile_Button.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.newfile_Button.setText("")
        self.newfile_Button.setObjectName("newfile_Button")
        self.settings_Button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_Button.setGeometry(QtCore.QRect(130, 10, 31, 31))
        self.settings_Button.setText("")
        self.settings_Button.setObjectName("settings_Button")
        self.resources_Button = QtWidgets.QPushButton(self.centralwidget)
        self.resources_Button.setGeometry(QtCore.QRect(170, 10, 31, 31))
        self.resources_Button.setText("")
        self.resources_Button.setObjectName("resources_Button")
        self.updateimg_Button = QtWidgets.QPushButton(self.centralwidget)
        self.updateimg_Button.setGeometry(QtCore.QRect(200, 10, 31, 31))
        self.updateimg_Button.setText("")
        self.updateimg_Button.setObjectName("updateimg_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actions_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACR v0.0.1"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.saveaction_Button.setText(_translate("MainWindow", "Save"))
        self.add_delay_Button.setText(_translate("MainWindow", "Add"))
        self.label_13.setText(_translate("MainWindow", "Delay"))
        self.delete_action_pushButton.setText(_translate("MainWindow", "Delete selected"))
        self.label_2.setText(_translate("MainWindow", "Image"))
        self.label_3.setText(_translate("MainWindow", "Button"))
        self.button_comboBox.setItemText(0, _translate("MainWindow", "Left"))
        self.button_comboBox.setItemText(1, _translate("MainWindow", "Middle"))
        self.button_comboBox.setItemText(2, _translate("MainWindow", "Right"))
        self.label_12.setText(_translate("MainWindow", "Duration (sec)"))
        self.label_16.setText(_translate("MainWindow", "Threshold"))
        self.label_50.setText(_translate("MainWindow", "Number of clicks"))
        self.label_51.setText(_translate("MainWindow", "Interval"))
        self.label_55.setText(_translate("MainWindow", "Index"))
        self.actions_tabWidget.setTabText(self.actions_tabWidget.indexOf(self.click_tab), _translate("MainWindow", "Click"))
        self.label_54.setText(_translate("MainWindow", "Interval"))
        self.actions_tabWidget.setTabText(self.actions_tabWidget.indexOf(self.print_tab), _translate("MainWindow", "Write"))
        self.add_hotkey_pushButton.setText(_translate("MainWindow", "Add"))
        self.add_hotkey_symbol_pushButton.setText(_translate("MainWindow", "Add"))
        self.delete_hotkey_pushButton.setText(_translate("MainWindow", "Delete"))
        self.actions_tabWidget.setTabText(self.actions_tabWidget.indexOf(self.press_tab), _translate("MainWindow", "Press"))
        self.actions_tabWidget.setTabText(self.actions_tabWidget.indexOf(self.scroll_tab), _translate("MainWindow", "Scroll"))
        self.label_4.setText(_translate("MainWindow", "Image"))
        self.label_18.setText(_translate("MainWindow", "Duration"))
        self.label_19.setText(_translate("MainWindow", "Threshold"))
        self.label_20.setText(_translate("MainWindow", "Index"))
        self.actions_tabWidget.setTabText(self.actions_tabWidget.indexOf(self.draganddrop_tab), _translate("MainWindow", "DragTo"))
        self.copy_action_pushButton.setText(_translate("MainWindow", "Copy selected"))
        self.new_action_puchButton.setText(_translate("MainWindow", "New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Actions"))
        self.label_14.setText(_translate("MainWindow", "Start / Stop button"))
        self.label_15.setText(_translate("MainWindow", "Display information"))
        self.start_Button.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Cycle"))
        self.label_52.setText(_translate("MainWindow", "Pause Button"))
        self.label_53.setText(_translate("MainWindow", "Actions interval"))
        self.label_9.setText(_translate("MainWindow", "Disable mouse"))
        self.label_5.setText(_translate("MainWindow", "Ignore errors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Start"))
